---
title: C26111
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 7550fb74ae5fb6e4a18ae2d7391dfca3cc0546f3
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 10/16/2019
ms.locfileid: "72448578"
---
# <a name="c26111"></a>C26111
경고 C 26111: 호출자가 잠금 \<lock > 해제 하지 못했습니다. 함수 \<func >를 호출 합니다.

 `_Requires_lock_not_held_` 주석에는 함수가 호출될 때 지정된 잠금에 대한 잠금 횟수가 0보다 클 수 없다는 사전 조건이 적용됩니다. 다른 함수를 호출하기 전에 함수가 잠금을 해제하지 못할 경우 경고 C26111이 발생합니다.

## <a name="example"></a>예제
 다음 예제에서는 잠긴 섹션 내에서 `_Requires_lock_not_held_`에 대한 호출로 인해 `DoNotLock` 사전 조건이 위반되기 때문에 경고 C26111이 발생합니다.

```

typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}
```
