---
title: C6320
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 3bcce7f19fa5b8515a47f4bbe27c0e05ddbae9e8
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 02/15/2020
ms.locfileid: "77266980"
---
# <a name="c6320"></a>C6320
경고 C6320: 예외 필터 식이 상수 EXCEPTION_EXECUTE_HANDLER입니다. 이렇게 하면 처리 하기에 적합 하지 않은 예외를 마스킹할 수 있습니다.

 이 경고는 __except 블록에서 EXCEPTION_EXECUTE_HANDLER 상수를 사용 하 여 파생 된 결과를 나타냅니다. 이 경우 \__except 블록의 문은 특정 함수에서 처리 하지 않으려는 예외를 포함 하 여 예외를 처리 하기 위해 항상 실행 됩니다. 예외를 처리 하기 전에 확인 하는 것이 좋습니다.

## <a name="example"></a>예제
 다음 코드는 __except 블록이 모든 형식의 예외를 처리 하려고 하기 때문에이 경고를 생성 합니다.

```cpp
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

 이 경고를 해결 하려면 다음 코드에 표시 된 대로 `GetExceptionCode`를 사용 하 여 특정 예외를 처리 하기 전에 확인 합니다.

```cpp
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>참고 항목
 [try-except 문](/cpp/cpp/try-except-statement)
